name: vaxcast_testing
description: Creating an actual server for VaxCast
version: 0.0.1
homepage: https://github.com/Dokotela/vaxcast_server

environment:
  sdk: '>=2.12.1 <3.0.0'
  
dependencies:
  build: ^2.0.1
  excel: ^2.0.0-null-safety-3
  vaxcast: 
    path: ../vaxcast

dev_dependencies:
  build_runner: ^2.0.2
