name: vax_cast
description: Vaccine Forecasting and Testing Tool Using Fhir Resources for Dart and Flutter

environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
  angel_framework: ^2.0.0
  angel_hot: ^2.0.6
  angel_configuration: ^2.0.0
  json_annotation: ^3.0.1
  date_utils: ^0.1.0+3
  http: ^0.12.0+4
  intl: ^0.16.1
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0
  fhir:
    path: fhir

dev_dependencies:
  json_serializable: ^3.2.5
  build_runner: ^1.8.1
  freezed: ^0.11.4
  test: ^1.15.3