name: vax_cast
description: Creating an actual server for VaxCast
version: 0.0.1
homepage: https://github.com/Dokotela/vax_cast_server

environment:
  sdk: '>=2.14.0 <3.0.0'
  
dependencies:
  collection: ^1.15.0
  date_utils: ^0.2.0
  fhir: ^0.5.0-3
  freezed_annotation: ^0.14.3

dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^0.14.3
  json_serializable: ^5.0.2