name: vaxcast
description: Creating an actual server for VaxCast
version: 0.0.1
homepage: https://github.com/Dokotela/vaxcast_server

environment:
  sdk: '>=2.15.0 <3.0.0'
  
dependencies:
  collection: ^1.15.0
  date_utils: ^0.2.0
  fhir: ^0.5.0-12
  freezed_annotation: ^1.1.0

dev_dependencies:
  test: ^1.20.1
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.3