name: vax_cast_server
description: Creating an actual server for VaxCast
version: 0.0.1
homepage: https://github.com/Dokotela/vax_cast_server

environment:
  sdk: '>=2.10.0 <3.0.0'
  
dependencies:
  fhir: ^0.1.5
  date_utils: ^0.1.0+3
  http: ^0.12.2
  mqtt_client: ^8.1.0