name: vax_cast_server
description: Creating an actual server for VaxCast
version: 0.0.1
homepage: https://github.com/Dokotela/vax_cast_server

environment:
  sdk: '>=2.12.1 <3.0.0'
  
dependencies:
  build: ^2.0.1
  dartz: ^0.10.0-nullsafety.2
  date_utils: ^0.2.0
  excel: ^2.0.0-null-safety-3
  fhir: ^0.4.6
  freezed_annotation: ^0.14.1
  http: ^0.13.3
  mqtt_client: ^9.3.1
  source_gen: ^1.0.0

dev_dependencies:

  build_config: ^1.0.0
  build_runner: ^2.0.2
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1